export const studies = [
  {
    slug: "articulated-form",
    number: "01",
    title: "Articulated form",
    category: "Linkages",
    kind: "linkage",
    color: "#e8e8e8",
    subtitle: "One motion. Endless configurations.",
    description:
      "Eight pivots follow four circular paths. The connections between them fold, stretch, and unfold into an ever-changing geometry. Adapted from the original reference composition.",
    principle: "Connected motion",
    parameter: "Orbit radius",
    min: 65,
    max: 110,
    initial: 92,
  },
  {
    slug: "endless-ascent",
    number: "02",
    title: "Endless ascent",
    category: "Illusions",
    kind: "stairs",
    color: "#e8e8e8",
    subtitle: "Always climbing. Never arriving.",
    description:
      "A small traveller traces an impossible staircase. Four flights appear to ascend into one another, turning a flat drawing into a quiet contradiction of space and perspective.",
    principle: "Impossible perspective",
    parameter: "Step depth",
    min: 10,
    max: 26,
    initial: 18,
  },
  {
    slug: "pendulum-wave",
    number: "03",
    title: "Pendulum wave",
    category: "Harmonics",
    kind: "pendulum",
    color: "#e8e8e8",
    subtitle: "Order slips into rhythm.",
    description:
      "Fifteen pendulums swing at slightly different frequencies. Starting together, they drift into travelling waves and intricate patterns before finding their way back into alignment.",
    principle: "Phase & frequency",
    parameter: "Swing amplitude",
    min: 10,
    max: 45,
    initial: 30,
  },
  {
    slug: "interference",
    number: "04",
    title: "Interference",
    category: "Geometry",
    kind: "moire",
    color: "#e8e8e8",
    subtitle: "A pattern between patterns.",
    description:
      "Two families of concentric circles move around one another. Their overlapping lines create fleeting patterns that seem to breathe, ripple, and turn with a life of their own.",
    principle: "Moiré patterns",
    parameter: "Circle separation",
    min: 15,
    max: 100,
    initial: 60,
  },
  {
    slug: "three-body-problem",
    number: "05",
    title: "Three-body problem",
    category: "Orbits",
    kind: "threebody",
    color: "#e8e8e8",
    subtitle: "Three bodies. One delicate balance.",
    description:
      "Three equal masses pull on one another, tracing the special figure-eight solution of the three-body problem. Their gravitational paths weave together in a repeating choreography. Adjust the trails to reveal the motion they leave behind.",
    principle: "Gravitational choreography",
    parameter: "Trail length",
    min: 30,
    max: 240,
    initial: 150,
  },
  {
    slug: "mobius-strip",
    number: "06",
    title: "Möbius strip",
    category: "Geometry",
    kind: "mobius",
    color: "#e8e8e8",
    subtitle: "Two sides become one.",
    description:
      "A ribbon closes with a single half-twist, creating one continuous surface. Follow the red marker: it takes two circuits to return to its starting point. Change the ribbon width and watch the rotating form reveal its geometry.",
    principle: "A continuous surface",
    parameter: "Ribbon width",
    min: 25,
    max: 100,
    initial: 75,
  },
  {
    slug: "gyroscope",
    number: "07",
    title: "Gyroscope",
    category: "Mechanisms",
    kind: "gyroscope",
    color: "#e8e8e8",
    subtitle: "A quiet balance of turning worlds.",
    description:
      "A brass rotor spins inside nested gimbal rings. The assembly slowly turns about its vertical axis while the rotor keeps its selected tilt. Explore this choreographed model of spin and precession: change the tilt to reveal how the rings and axle fit together.",
    principle: "Spin & precession",
    parameter: "Axis tilt (°)",
    min: 10,
    max: 80,
    initial: 38,
  },
  {
    slug: "rolling-cube",
    number: "08",
    title: "Rolling cube",
    category: "Geometry",
    kind: "rollingcube",
    color: "#e8e8e8",
    subtitle: "One layer leads. The whole follows.",
    description:
      "A wireframe cube separates into square layers. Each rolls a quarter-turn over its lower edge, one after another, until the cube comes together on its next face. The view follows its progress as the sequence continues. Change the number of layers to reshape the rhythm.",
    principle: "Sequential rotation",
    parameter: "Layers",
    min: 3,
    max: 12,
    initial: 7,
  },
  {
    slug: "rolling-wave",
    number: "09",
    title: "Rolling wave",
    category: "Geometry",
    kind: "rollingwave",
    color: "#050505",
    subtitle: "A wave with no beginning or end.",
    description:
      "A ring of solid bars lifts and settles in sequence. A rolling crest travels continuously around the circle, revealing blue end caps against dark faces. Change the number of bars to explore a denser or more open rhythm.",
    principle: "Sequential rotation",
    parameter: "Bars",
    min: 18,
    max: 42,
    initial: 30,
  },
  {
    slug: "tesseract",
    number: "10",
    title: "Tesseract",
    category: "Geometry",
    kind: "tesseract",
    color: "#e8e8e8",
    subtitle: "A glimpse beyond three dimensions.",
    description:
      "Sixteen vertices and thirty-two edges rotate through four-dimensional space. A perspective projection turns the hypercube into shifting, nested forms. Blue edges connect its two cubic halves. Adjust the projection distance to change the apparent depth.",
    principle: "Four-dimensional rotation",
    parameter: "Projection distance",
    min: 4,
    max: 10,
    initial: 6,
  },
  {
    slug: "impossible-triangle",
    number: "11",
    title: "Impossible triangle",
    category: "Illusions",
    kind: "triangle",
    color: "#e8e8e8",
    subtitle: "Perspective holds it together.",
    description:
      "Three beams appear to meet in an impossible triangle. As the assembly turns, gaps reveal the construction behind the illusion; the frontal view brings it together again. Adjust the reveal angle to look further around the form.",
    principle: "Forced perspective",
    parameter: "Reveal angle (°)",
    min: 20,
    max: 75,
    initial: 60,
  },
  {
    slug: "spirograph",
    number: "12",
    title: "Spirograph",
    category: "Harmonics",
    kind: "spirograph",
    color: "#e8e8e8",
    subtitle: "Circles drawing something new.",
    description:
      "A small circle rolls inside a larger one, carrying a pen that traces a five-fold looping curve. Move the pen away from the rolling circle’s center to transform gentle lobes into intersecting loops. Construction guides reveal the mechanism.",
    principle: "Rolling-circle curves",
    parameter: "Pen offset",
    min: 10,
    max: 75,
    initial: 58,
  },
  {
    slug: "epicycles",
    number: "13",
    title: "Epicycles",
    category: "Harmonics",
    kind: "epicycles",
    color: "#e8e8e8",
    subtitle: "Small circles. A larger picture.",
    description:
      "A chain of rotating arms adds circular motions at different frequencies. Its tip traces the resulting Fourier curve. Add more harmonics to introduce finer loops, or hide the guide circles to follow the drawing alone.",
    principle: "Fourier synthesis",
    parameter: "Harmonics",
    min: 2,
    max: 10,
    initial: 6,
  },
  {
    slug: "chladni-patterns",
    number: "14",
    title: "Chladni patterns",
    category: "Harmonics",
    kind: "chladni",
    color: "#e8e8e8",
    subtitle: "Stillness, shaped by vibration.",
    description:
      "Grains gather along the quiet nodal lines of an idealized square-plate vibration pattern. This mathematical illustration follows the field toward zero, then redistributes the grains to repeat. Select a plate mode to discover a different symmetry.",
    principle: "Nodal geometry",
    parameter: "Plate mode",
    min: 1,
    max: 7,
    initial: 3,
  },
  {
    slug: "kaleidoscope",
    number: "15",
    title: "Kaleidoscope",
    category: "Geometry",
    kind: "kaleidoscope",
    color: "#e8e8e8",
    subtitle: "One fragment. Infinite reflections.",
    description:
      "Drifting pieces of color reflect across a circle of mirrors. Each neighbouring sector reverses the same moving shapes, creating an ever-changing radial pattern. Adjust the mirror pairs to change its symmetry.",
    principle: "Reflection & symmetry",
    parameter: "Mirror pairs",
    min: 3,
    max: 12,
    initial: 6,
  },
  {
    slug: "rolling-polygons",
    number: "16",
    title: "Rolling polygons",
    category: "Mechanisms",
    kind: "polygons",
    color: "#e8e8e8",
    subtitle: "Every edge takes its turn.",
    description:
      "A regular polygon tips over each leading corner and lands on its next edge. The view follows its forward travel while a yellow-lime vertex traces the motion. Change the number of sides to see a triangle’s pronounced tumble become a gentler roll.",
    principle: "Edge-by-edge motion",
    parameter: "Sides",
    min: 3,
    max: 10,
    initial: 5,
  },
  {
    slug: "iris-mechanism",
    number: "17",
    title: "Iris mechanism",
    category: "Mechanisms",
    kind: "iris",
    color: "#e8e8e8",
    subtitle: "Many blades. One opening.",
    description:
      "Nine blade edges rotate around fixed pivots to form a polygonal aperture. A blue edge reveals their coordinated movement. Adjust the maximum opening as the aperture expands and contracts.",
    principle: "Coordinated aperture",
    parameter: "Maximum opening",
    min: 25,
    max: 100,
    initial: 85,
  },
  {
    slug: "trammel-of-archimedes",
    number: "18",
    title: "Trammel of Archimedes",
    category: "Mechanisms",
    kind: "trammel",
    color: "#e8e8e8",
    subtitle: "Two straight paths draw a curve.",
    description:
      "Two sliders travel along perpendicular tracks, joined by a rigid bar. A pen extending beyond the sliders traces an exact ellipse. Adjust the pen reach to change the curve’s proportions while the slider spacing stays fixed.",
    principle: "Elliptical motion",
    parameter: "Pen reach",
    min: 25,
    max: 95,
    initial: 72,
  },
  {
    slug: "phyllotaxis-spiral",
    number: "19",
    title: "Phyllotaxis spiral",
    category: "Geometry",
    kind: "phyllotaxis",
    color: "#e8e8e8",
    subtitle: "A small angle. A natural order.",
    description:
      "Hundreds of seeds follow a square-root radial spacing and the golden angle, forming the interwoven spirals seen in seed heads. A gentle angular variation rearranges the pattern as it rotates. Adjust the divergence offset to explore neighbouring arrangements; gold seeds mark every thirty-fourth step.",
    principle: "Golden-angle growth",
    parameter: "Divergence offset (°)",
    min: -8,
    max: 8,
    initial: 0,
  },
  {
    slug: "articulated-hexagon",
    number: "20",
    title: "Articulated hexagon",
    category: "Linkages",
    kind: "hexagon",
    color: "#e8e8e8",
    subtitle: "Six pivots. New intersections.",
    description:
      "Six pivots orbit a ring of guide circles, with neighbours turning in opposite directions. A teal hexagon folds around two interlaced triangles; gold points mark the crossings of opposing diagonals. Adjust the orbit radius to change how deeply the forms intersect.",
    principle: "Intersecting geometry",
    parameter: "Orbit radius",
    min: 25,
    max: 72,
    initial: 52,
  },
  {
    slug: "geneva-drive",
    number: "21",
    title: "Geneva drive",
    category: "Mechanisms",
    kind: "geneva",
    color: "#e8e8e8",
    subtitle: "Continuous motion. Measured steps.",
    description:
      "A rotating pin enters successive slots in a wheel, advancing it one step before withdrawing. This kinematic illustration isolates the pin-and-slot motion: the output rests between engagements. Change the slot count to reshape the rhythm; the pin turns blue while engaged.",
    principle: "Intermittent rotation",
    parameter: "Slots",
    min: 4,
    max: 8,
    initial: 5,
  },
  {
    slug: "miura-fold",
    number: "22",
    title: "Miura fold",
    category: "Geometry",
    kind: "miura",
    color: "#e8e8e8",
    subtitle: "One crease moves the whole.",
    description:
      "A sheet of rigid parallelograms folds and unfolds as one connected surface. Its panels keep their lengths and angles while the sheet contracts in two directions. Adjust the maximum fold angle to change its breathing motion; construction guides highlight the crease network.",
    principle: "Rigid origami",
    parameter: "Maximum fold angle (°)",
    min: 10,
    max: 60,
    initial: 52,
  },
  {
    slug: "branching-rules",
    number: "23",
    title: "Branching rules",
    category: "Growth",
    kind: "branching",
    color: "#e8e8e8",
    subtitle: "A small instruction becomes a tree.",
    description:
      "Each branch produces two shorter branches, repeating the same rule across seven generations. The structure grows from its trunk to its tips, pauses, and fades before beginning again. Change the branch angle to turn a narrow crown into a spreading canopy. Guides mark the branch tips and central axis.",
    principle: "Recursive growth",
    parameter: "Branch angle (°)",
    min: 15,
    max: 45,
    initial: 28,
  },
  {
    slug: "collective-motion",
    number: "24",
    title: "Collective motion",
    category: "Emergence",
    kind: "flock",
    color: "#e8e8e8",
    subtitle: "No leader. A shared direction.",
    description:
      "Ninety agents steer to avoid close neighbors, gather locally, and align their headings. Together these rules create a changing flock in a space that wraps at its edges. Adjust alignment strength to restart the same initial arrangement with a new balance of behavior. Guides reveal one agent’s neighborhood and heading.",
    principle: "Local rules, collective behavior",
    parameter: "Alignment strength",
    min: 0,
    max: 100,
    initial: 55,
  },
  {
    slug: "gravity-well",
    number: "25",
    title: "Gravity well",
    category: "Orbits",
    kind: "gravity",
    color: "#e8e8e8",
    subtitle: "Always falling. Never landing.",
    description:
      "Three bodies coast across a surface shaped by a single central mass, each ignoring the others. The mass is softened at its core, so no path closes into a perfect ellipse: every orbit turns a little each time it swings back, tracing a slow rosette. Increase the mass to deepen the well and send the same starting paths into tighter, faster plunges. Guides mark one orbit’s nearest and farthest reach and its heading.",
    principle: "Apsidal precession",
    parameter: "Central mass",
    min: 40,
    max: 100,
    initial: 70,
  },
  {
    slug: "prism",
    number: "26",
    title: "Prism",
    category: "Optics",
    kind: "prism",
    color: "#e8e8e8",
    subtitle: "One beam in. Every colour out.",
    description:
      "A beam of white light bends as it enters a glass prism and bends again as it leaves. Glass slows violet light more than red, so each wavelength turns by a slightly different angle and the beam fans into a spectrum on the screen. A lamp swings below and to the left of the prism, changing where and how steeply the beam strikes it, and the spectrum climbs and falls on the screen as the angle passes through least deviation. Widen the apex angle to spread the colours further, until at the steepest angles the most strongly bent light is trapped by total internal reflection. Guides draw the surface normals and the laws behind each turn.",
    principle: "Refraction and dispersion",
    parameter: "Apex angle (°)",
    min: 30,
    max: 65,
    initial: 55,
  },
] as const
export type Study = (typeof studies)[number]
