export const studies = [
  {
    slug: "articulated-form",
    number: "01",
    title: "Articulated form",
    category: "Linkages",
    kind: "linkage",
    color: "#e8e8e8",
    subtitle: "One motion. Endless configurations.",
    description:
      "Eight pivots follow four circular paths. The connections between them fold, stretch, and unfold into an ever-changing geometry. Adapted from the original reference composition.",
    principle: "Connected motion",
    parameter: "Orbit radius",
    min: 65,
    max: 110,
    initial: 92,
  },
  {
    slug: "endless-ascent",
    number: "02",
    title: "Endless ascent",
    category: "Illusions",
    kind: "stairs",
    color: "#e8e8e8",
    subtitle: "Always climbing. Never arriving.",
    description:
      "A small traveller traces an impossible staircase. Four flights appear to ascend into one another, turning a flat drawing into a quiet contradiction of space and perspective.",
    principle: "Impossible perspective",
    parameter: "Step depth",
    min: 10,
    max: 26,
    initial: 18,
  },
  {
    slug: "pendulum-wave",
    number: "03",
    title: "Pendulum wave",
    category: "Harmonics",
    kind: "pendulum",
    color: "#e8e8e8",
    subtitle: "Order slips into rhythm.",
    description:
      "Fifteen pendulums swing at slightly different frequencies. Starting together, they drift into travelling waves and intricate patterns before finding their way back into alignment.",
    principle: "Phase & frequency",
    parameter: "Swing amplitude",
    min: 10,
    max: 45,
    initial: 30,
  },
  {
    slug: "interference",
    number: "04",
    title: "Interference",
    category: "Geometry",
    kind: "moire",
    color: "#e8e8e8",
    subtitle: "A pattern between patterns.",
    description:
      "Two families of concentric circles move around one another. Their overlapping lines create fleeting patterns that seem to breathe, ripple, and turn with a life of their own.",
    principle: "Moiré patterns",
    parameter: "Circle separation",
    min: 15,
    max: 100,
    initial: 60,
  },
  {
    slug: "three-body-problem",
    number: "05",
    title: "Three-body problem",
    category: "Orbits",
    kind: "threebody",
    color: "#e8e8e8",
    subtitle: "Three bodies. One delicate balance.",
    description:
      "Three equal masses pull on one another, tracing the special figure-eight solution of the three-body problem. Their gravitational paths weave together in a repeating choreography. Adjust the trails to reveal the motion they leave behind.",
    principle: "Gravitational choreography",
    parameter: "Trail length",
    min: 30,
    max: 240,
    initial: 150,
  },
  {
    slug: "mobius-strip",
    number: "06",
    title: "Möbius strip",
    category: "Geometry",
    kind: "mobius",
    color: "#e8e8e8",
    subtitle: "Two sides become one.",
    description:
      "A ribbon closes with a single half-twist, creating one continuous surface. Follow the red marker: it takes two circuits to return to its starting point. Change the ribbon width and watch the rotating form reveal its geometry.",
    principle: "A continuous surface",
    parameter: "Ribbon width",
    min: 25,
    max: 100,
    initial: 75,
  },
  {
    slug: "gyroscope",
    number: "07",
    title: "Gyroscope",
    category: "Mechanisms",
    kind: "gyroscope",
    color: "#e8e8e8",
    subtitle: "A quiet balance of turning worlds.",
    description:
      "A brass rotor spins inside nested gimbal rings. The assembly slowly turns about its vertical axis while the rotor keeps its selected tilt. Explore this choreographed model of spin and precession: change the tilt to reveal how the rings and axle fit together.",
    principle: "Spin & precession",
    parameter: "Axis tilt (°)",
    min: 10,
    max: 80,
    initial: 38,
  },
  {
    slug: "rolling-cube",
    number: "08",
    title: "Rolling cube",
    category: "Geometry",
    kind: "rollingcube",
    color: "#e8e8e8",
    subtitle: "One layer leads. The whole follows.",
    description:
      "A wireframe cube separates into square layers. Each rolls a quarter-turn over its lower edge, one after another, until the cube comes together on its next face. The view follows its progress as the sequence continues. Change the number of layers to reshape the rhythm.",
    principle: "Sequential rotation",
    parameter: "Layers",
    min: 3,
    max: 12,
    initial: 7,
  },
  {
    slug: "rolling-wave",
    number: "09",
    title: "Rolling wave",
    category: "Geometry",
    kind: "rollingwave",
    color: "#050505",
    subtitle: "A wave with no beginning or end.",
    description:
      "A ring of solid bars lifts and settles in sequence. A rolling crest travels continuously around the circle, revealing blue end caps against dark faces. Change the number of bars to explore a denser or more open rhythm.",
    principle: "Sequential rotation",
    parameter: "Bars",
    min: 18,
    max: 42,
    initial: 30,
  },
  {
    slug: "tesseract",
    number: "10",
    title: "Tesseract",
    category: "Geometry",
    kind: "tesseract",
    color: "#e8e8e8",
    subtitle: "A glimpse beyond three dimensions.",
    description:
      "Sixteen vertices and thirty-two edges rotate through four-dimensional space. A perspective projection turns the hypercube into shifting, nested forms. Blue edges connect its two cubic halves. Adjust the projection distance to change the apparent depth.",
    principle: "Four-dimensional rotation",
    parameter: "Projection distance",
    min: 4,
    max: 10,
    initial: 6,
  },
  {
    slug: "impossible-triangle",
    number: "11",
    title: "Impossible triangle",
    category: "Illusions",
    kind: "triangle",
    color: "#e8e8e8",
    subtitle: "Perspective holds it together.",
    description:
      "Three beams appear to meet in an impossible triangle. As the assembly turns, gaps reveal the construction behind the illusion; the frontal view brings it together again. Adjust the reveal angle to look further around the form.",
    principle: "Forced perspective",
    parameter: "Reveal angle (°)",
    min: 20,
    max: 75,
    initial: 60,
  },
  {
    slug: "spirograph",
    number: "12",
    title: "Spirograph",
    category: "Harmonics",
    kind: "spirograph",
    color: "#e8e8e8",
    subtitle: "Circles drawing something new.",
    description:
      "A small circle rolls inside a larger one, carrying a pen that traces a five-fold looping curve. Move the pen away from the rolling circle’s center to transform gentle lobes into intersecting loops. Construction guides reveal the mechanism.",
    principle: "Rolling-circle curves",
    parameter: "Pen offset",
    min: 10,
    max: 75,
    initial: 58,
  },
  {
    slug: "epicycles",
    number: "13",
    title: "Epicycles",
    category: "Harmonics",
    kind: "epicycles",
    color: "#e8e8e8",
    subtitle: "Small circles. A larger picture.",
    description:
      "A chain of rotating arms adds circular motions at different frequencies. Its tip traces the resulting Fourier curve. Add more harmonics to introduce finer loops, or hide the guide circles to follow the drawing alone.",
    principle: "Fourier synthesis",
    parameter: "Harmonics",
    min: 2,
    max: 10,
    initial: 6,
  },
  {
    slug: "chladni-patterns",
    number: "14",
    title: "Chladni patterns",
    category: "Harmonics",
    kind: "chladni",
    color: "#e8e8e8",
    subtitle: "Stillness, shaped by vibration.",
    description:
      "Grains gather along the quiet nodal lines of an idealized square-plate vibration pattern. This mathematical illustration follows the field toward zero, then redistributes the grains to repeat. Select a plate mode to discover a different symmetry.",
    principle: "Nodal geometry",
    parameter: "Plate mode",
    min: 1,
    max: 7,
    initial: 3,
  },
  {
    slug: "kaleidoscope",
    number: "15",
    title: "Kaleidoscope",
    category: "Geometry",
    kind: "kaleidoscope",
    color: "#e8e8e8",
    subtitle: "One fragment. Infinite reflections.",
    description:
      "Drifting pieces of color reflect across a circle of mirrors. Each neighbouring sector reverses the same moving shapes, creating an ever-changing radial pattern. Adjust the mirror pairs to change its symmetry.",
    principle: "Reflection & symmetry",
    parameter: "Mirror pairs",
    min: 3,
    max: 12,
    initial: 6,
  },
  {
    slug: "rolling-polygons",
    number: "16",
    title: "Rolling polygons",
    category: "Mechanisms",
    kind: "polygons",
    color: "#e8e8e8",
    subtitle: "Every edge takes its turn.",
    description:
      "A regular polygon tips over each leading corner and lands on its next edge. The view follows its forward travel while a yellow-lime vertex traces the motion. Change the number of sides to see a triangle’s pronounced tumble become a gentler roll.",
    principle: "Edge-by-edge motion",
    parameter: "Sides",
    min: 3,
    max: 10,
    initial: 5,
  },
] as const
export type Study = (typeof studies)[number]
