export const studies = [
  {
    slug: "articulated-form",
    number: "01",
    title: "Articulated form",
    category: "Linkages",
    kind: "linkage",
    color: "#e9ece3",
    subtitle: "One motion. Endless configurations.",
    description:
      "Eight pivots follow four circular paths. The connections between them fold, stretch, and unfold into an ever-changing geometry. Adapted from the original reference composition.",
    principle: "Connected motion",
    parameter: "Orbit radius",
    min: 65,
    max: 110,
    initial: 92,
  },
  {
    slug: "endless-ascent",
    number: "02",
    title: "Endless ascent",
    category: "Illusions",
    kind: "stairs",
    color: "#eee7dd",
    subtitle: "Always climbing. Never arriving.",
    description:
      "A small traveller traces an impossible staircase. Four flights appear to ascend into one another, turning a flat drawing into a quiet contradiction of space and perspective.",
    principle: "Impossible perspective",
    parameter: "Step depth",
    min: 10,
    max: 26,
    initial: 18,
  },
  {
    slug: "pendulum-wave",
    number: "03",
    title: "Pendulum wave",
    category: "Harmonics",
    kind: "pendulum",
    color: "#e5eaf0",
    subtitle: "Order slips into rhythm.",
    description:
      "Fifteen pendulums swing at slightly different frequencies. Starting together, they drift into travelling waves and intricate patterns before finding their way back into alignment.",
    principle: "Phase & frequency",
    parameter: "Swing amplitude",
    min: 10,
    max: 45,
    initial: 30,
  },
  {
    slug: "interference",
    number: "04",
    title: "Interference",
    category: "Geometry",
    kind: "moire",
    color: "#ede5e1",
    subtitle: "A pattern between patterns.",
    description:
      "Two families of concentric circles move around one another. Their overlapping lines create fleeting patterns that seem to breathe, ripple, and turn with a life of their own.",
    principle: "Moiré patterns",
    parameter: "Circle separation",
    min: 15,
    max: 100,
    initial: 60,
  },
  {
    slug: "three-body-problem",
    number: "05",
    title: "Three-body problem",
    category: "Orbits",
    kind: "threebody",
    color: "#eae9de",
    subtitle: "Three bodies. One delicate balance.",
    description:
      "Three equal masses pull on one another, tracing the special figure-eight solution of the three-body problem. Their gravitational paths weave together in a repeating choreography. Adjust the trails to reveal the motion they leave behind.",
    principle: "Gravitational choreography",
    parameter: "Trail length",
    min: 30,
    max: 240,
    initial: 150,
  },
  {
    slug: "mobius-strip",
    number: "06",
    title: "Möbius strip",
    category: "Geometry",
    kind: "mobius",
    color: "#eae5ed",
    subtitle: "Two sides become one.",
    description:
      "A ribbon closes with a single half-twist, creating one continuous surface. Follow the golden marker: it takes two circuits to return to its starting point. Change the ribbon width and watch the rotating form reveal its geometry.",
    principle: "A continuous surface",
    parameter: "Ribbon width",
    min: 25,
    max: 100,
    initial: 75,
  },
  {
    slug: "gyroscope",
    number: "07",
    title: "Gyroscope",
    category: "Mechanisms",
    kind: "gyroscope",
    color: "#e3eae5",
    subtitle: "A quiet balance of turning worlds.",
    description:
      "A brass rotor spins inside nested gimbal rings. The assembly slowly turns about its vertical axis while the rotor keeps its selected tilt. Explore this choreographed model of spin and precession: change the tilt to reveal how the rings and axle fit together.",
    principle: "Spin & precession",
    parameter: "Axis tilt (°)",
    min: 10,
    max: 80,
    initial: 38,
  },
] as const
export type Study = (typeof studies)[number]
